FROM node:17.5-alpine3.14

ENV NODE_ENV=development

WORKDIR /app

COPY package.json .
RUN yarn install

COPY tsconfig.json next.config.js next-env.d.ts tailwind.config.js tailwind.css postcss.config.js ./

CMD yarn dev
