version: "3.8"

# Reminder:
# Ports are in the format: <inner>:<outer> ??

services:
  db:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: "forms"
      POSTGRES_USER: "forms"
      POSTGRES_PASSWORD: "forms"
    ports:
      - "5433:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - ./backend/src:/app/src
