FROM node:17.0-alpine3.14

ENV NODE_ENV=development

WORKDIR /app

COPY ["package.json", "./"]

RUN ["yarn", "install", "--development"]

COPY [".", "."]

RUN ["yarn", "generate"]

RUN ["yarn", "build"]

CMD ["yarn", "dev"]