FROM node:17.5-alpine3.14

ENV NODE_ENV=development
ENV TSC_WATCHFILE=true

WORKDIR /app

COPY package.json .
RUN yarn install

COPY ./prisma/schema.prisma ./prisma/schema.prisma
RUN yarn generate

COPY tsconfig.json .

CMD yarn dev
